# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\help.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AboutForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 111)
        self.help_label = QtWidgets.QLabel(Form)
        self.help_label.setGeometry(QtCore.QRect(40, 30, 321, 20))
        self.help_label.setObjectName("help_label")
        self.back_btn = QtWidgets.QPushButton(Form)
        self.back_btn.setGeometry(QtCore.QRect(160, 80, 75, 23))
        self.back_btn.setObjectName("back_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "справка"))
        self.help_label.setText(_translate("Form", "Это маленькая программа для обучения языкам. Удачи!"))
        self.back_btn.setText(_translate("Form", "Назад"))
