# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_language.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AddLangForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(301, 125)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 20, 281, 81))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_lang_label = QtWidgets.QLabel(self.widget)
        self.add_lang_label.setObjectName("add_lang_label")
        self.verticalLayout.addWidget(self.add_lang_label)
        self.add_lang_edit = QtWidgets.QLineEdit(self.widget)
        self.add_lang_edit.setObjectName("add_lang_edit")
        self.verticalLayout.addWidget(self.add_lang_edit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_btn = QtWidgets.QPushButton(self.widget)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.cansel_btn = QtWidgets.QPushButton(self.widget)
        self.cansel_btn.setObjectName("cansel_btn")
        self.horizontalLayout.addWidget(self.cansel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "WordTrainer - Добавить язык"))
        self.add_lang_label.setText(_translate("Form", "Добавить язык"))
        self.add_btn.setText(_translate("Form", "Добавить"))
        self.cansel_btn.setText(_translate("Form", "Отмена"))
