# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_word.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AddWordForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(301, 125)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 280, 102))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.adding_word_label = QtWidgets.QLabel(self.widget)
        self.adding_word_label.setObjectName("adding_word_label")
        self.verticalLayout_2.addWidget(self.adding_word_label)
        self.add_word_edit = QtWidgets.QLineEdit(self.widget)
        self.add_word_edit.setObjectName("add_word_edit")
        self.verticalLayout_2.addWidget(self.add_word_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.russian_translation_label = QtWidgets.QLabel(self.widget)
        self.russian_translation_label.setObjectName("russian_translation_label")
        self.verticalLayout.addWidget(self.russian_translation_label)
        self.add_translation_edit = QtWidgets.QLineEdit(self.widget)
        self.add_translation_edit.setObjectName("add_translation_edit")
        self.verticalLayout.addWidget(self.add_translation_edit)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.lang_choose = QtWidgets.QComboBox(self.widget)
        self.lang_choose.setObjectName("lang_choose")
        self.verticalLayout_3.addWidget(self.lang_choose)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_button = QtWidgets.QPushButton(self.widget)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        self.cansel_button = QtWidgets.QPushButton(self.widget)
        self.cansel_button.setObjectName("cansel_button")
        self.horizontalLayout.addWidget(self.cansel_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "WordTrainer - Добавить слово"))
        self.adding_word_label.setText(_translate("Form", "Слово"))
        self.russian_translation_label.setText(_translate("Form", "Перевод на русский"))
        self.add_button.setText(_translate("Form", "Добавить"))
        self.cansel_button.setText(_translate("Form", "Отмена"))
