# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dictionary.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class DictForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1271, 902)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 50, 1191, 791))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dictionary_language_choose = QtWidgets.QComboBox(self.layoutWidget)
        self.dictionary_language_choose.setObjectName("dictionary_language_choose")
        self.verticalLayout.addWidget(self.dictionary_language_choose)
        self.dict_view = QtWidgets.QTableWidget(self.layoutWidget)
        self.dict_view.setObjectName("dict_view")
        self.dict_view.setColumnCount(0)
        self.dict_view.setRowCount(0)
        self.verticalLayout.addWidget(self.dict_view)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(41, 850, 165, 35))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.word_add_button = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.word_add_button.setFont(font)
        self.word_add_button.setObjectName("word_add_button")
        self.horizontalLayout_2.addWidget(self.word_add_button)
        self.add_word_label = QtWidgets.QLabel(self.layoutWidget1)
        self.add_word_label.setObjectName("add_word_label")
        self.horizontalLayout_2.addWidget(self.add_word_label)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(228, 850, 161, 35))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.land_add_button = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.land_add_button.setFont(font)
        self.land_add_button.setObjectName("land_add_button")
        self.horizontalLayout_3.addWidget(self.land_add_button)
        self.add_lang_label = QtWidgets.QLabel(self.layoutWidget2)
        self.add_lang_label.setObjectName("add_lang_label")
        self.horizontalLayout_3.addWidget(self.add_lang_label)
        self.back_to_main_menu_button = QtWidgets.QPushButton(Form)
        self.back_to_main_menu_button.setGeometry(QtCore.QRect(960, 850, 271, 40))
        self.back_to_main_menu_button.setObjectName("back_to_main_menu_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "WordTrainer - словарь"))
        self.word_add_button.setText(_translate("Form", "+"))
        self.add_word_label.setText(_translate("Form", "Добавить слово"))
        self.land_add_button.setText(_translate("Form", "+"))
        self.add_lang_label.setText(_translate("Form", "Добавить язык"))
        self.back_to_main_menu_button.setText(_translate("Form", "В главное меню"))
