# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class SettingsForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(371, 132)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 30, 275, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.light_theme_btn = QtWidgets.QRadioButton(self.layoutWidget)
        self.light_theme_btn.setChecked(True)
        self.light_theme_btn.setObjectName("light_theme_btn")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.light_theme_btn)
        self.horizontalLayout.addWidget(self.light_theme_btn)
        self.dark_theme_btn = QtWidgets.QRadioButton(self.layoutWidget)
        self.dark_theme_btn.setObjectName("dark_theme_btn")
        self.buttonGroup.addButton(self.dark_theme_btn)
        self.horizontalLayout.addWidget(self.dark_theme_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.save_button = QtWidgets.QPushButton(self.layoutWidget)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_2.addWidget(self.save_button)
        self.cansel_button = QtWidgets.QPushButton(self.layoutWidget)
        self.cansel_button.setObjectName("cansel_button")
        self.horizontalLayout_2.addWidget(self.cansel_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "WordTrainer - настройки"))
        self.label.setText(_translate("Form", "Настроить тему"))
        self.light_theme_btn.setText(_translate("Form", "Светлая"))
        self.dark_theme_btn.setText(_translate("Form", "Тёмная"))
        self.save_button.setText(_translate("Form", "Сохранить"))
        self.cansel_button.setText(_translate("Form", "Отмена"))
