# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\train.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TrainingForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1271, 902)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(390, 360, 401, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.word_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.word_edit.setEnabled(False)
        self.word_edit.setObjectName("word_edit")
        self.horizontalLayout.addWidget(self.word_edit)
        self.word_in_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.word_in_edit.setObjectName("word_in_edit")
        self.horizontalLayout.addWidget(self.word_in_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.answer_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.answer_btn.setObjectName("answer_btn")
        self.verticalLayout.addWidget(self.answer_btn)
        self.finish_btn = QtWidgets.QPushButton(Form)
        self.finish_btn.setGeometry(QtCore.QRect(60, 790, 161, 51))
        self.finish_btn.setObjectName("finish_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "WordTrainer - треннировка"))
        self.answer_btn.setText(_translate("Form", "Ответ"))
        self.finish_btn.setText(_translate("Form", "Прервать треннировку"))
