# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\train_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TrainingSettingsDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(282, 180)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 261, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.translate_label = QtWidgets.QLabel(self.layoutWidget)
        self.translate_label.setObjectName("translate_label")
        self.verticalLayout.addWidget(self.translate_label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.from_label = QtWidgets.QLabel(self.layoutWidget)
        self.from_label.setObjectName("from_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.from_label)
        self.choose_lang_box = QtWidgets.QComboBox(self.layoutWidget)
        self.choose_lang_box.setObjectName("choose_lang_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.choose_lang_box)
        self.n_of_words_label = QtWidgets.QLabel(self.layoutWidget)
        self.n_of_words_label.setObjectName("n_of_words_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.n_of_words_label)
        self.n_of_words_edit = QtWidgets.QSpinBox(self.layoutWidget)
        self.n_of_words_edit.setMinimum(1)
        self.n_of_words_edit.setObjectName("n_of_words_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.n_of_words_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout.addWidget(self.start_btn)
        self.back_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout.addWidget(self.back_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "WordTrainer - настройки треннировки"))
        self.translate_label.setText(_translate("Dialog", "Переводить"))
        self.from_label.setText(_translate("Dialog", "с языка"))
        self.choose_lang_box.setCurrentText(_translate("Dialog", "Английский"))
        self.n_of_words_label.setText(_translate("Dialog", "Количество слов"))
        self.start_btn.setText(_translate("Dialog", "Старт!"))
        self.back_btn.setText(_translate("Dialog", "Назад"))
